### ISSUE TITLE
[missing dependencies] qt5-quick3d

### ISSUE THREAD

**Issue by zsvzsv** [JaGoLi/ytdl-gui#9] opened 2021-01-19 14:44 UTC
cd src; \
qmake; \
make -j`nproc`
Info: creating stash file /home/user/.cache/yay/youtubedl-gui/src/ytdl-gui/src/.qmake.stash
Project ERROR: Unknown module(s) in QT: quick

**Comment by JaGoLi** [comment] 2021-01-19 16:19
Can you try to see if the issue is resolved with "qt5-quickcontrols" as dependency? I have gotten a comment on the aur saying that fixes it.

**Comment by JaGoLi** [comment] 2021-01-19 18:33
Are you on debian or arch?

**Comment by zsvzsv** [comment] 2021-01-19 19:38
> Are you on debian or arch?

Arch. Adding qt5-quick3d or qt5-quickcontrols will work

**Comment by JaGoLi** [comment] 2021-01-19 22:47
Thanks for the feedback. I will add qt5-quickcontrols as a build dependency for the Arch linux package. I will close the issue once it's done.

**Comment by JaGoLi** [comment] 2021-01-20 15:02
Updated both beta and standard arch linux PKGBUILDS

**Closed by JaGoLi** 2021-01-20 15:02 UTC
