### ISSUE TITLE
UX: 'Download Succeeded' window should not be modal

### ISSUE THREAD

**Issue by nobodysu** [JaGoLi/ytdl-gui#51] opened 2021-08-17 15:18 UTC
Or just should not pop up when main window is not active. In current behavior it interrupts user activity in other windows.

**Comment by JaGoLi** [comment] 2021-08-23 16:48
What about if a download fails? Should that be modal or not in your view?

**Comment by nobodysu** [comment] 2021-08-23 17:09
The point is: no notification should activate the main window. If it's not possible in Qt to suppress that - nothing should be modal.

Steps to reproduce:
- start large download
- do things in other windows while waiting for download to finish
- swear when download finishes

**Comment by JaGoLi** [comment] 2021-08-30 01:49
I have found an what is in my mind an elegant compromise. I have decided that if the youtube downloader is not the active window and the download succeeds, then there is no popup notification. However, I have decided to keep it in case of a failure. The message will still remain if downloader is in focus. I agree with you that it was very annoying in the case of long downloads.

**Comment by JaGoLi** [comment] 2021-08-30 01:50
I also experimented with having the popup window be active on a timer, but it was also too distracting. Let me know what you think. You can try it in the beta branch. Also, just letting you know that this is the final feature that I will be working on before having an official 3.0 release.

**Comment by JaGoLi** [comment] 2021-08-30 13:51
I'm closing this issue. I'm confident that the problem is solved.

**Closed by JaGoLi** 2021-08-30 13:51 UTC
